//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsZone
{
    using System;
    using System.Collections.Generic;
    
    public partial class club_games
    {
        public int id { get; set; }
        public int clubid { get; set; }
        public int gameid { get; set; }
    
        public virtual club club { get; set; }
        public virtual game game { get; set; }
    }
}
