//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsZone
{
    using System;
    using System.Collections.Generic;
    
    public partial class coach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public coach()
        {
            this.coach_associations = new HashSet<coach_associations>();
            this.coach_associations_request = new HashSet<coach_associations_request>();
        }
    
        public int coachid { get; set; }
        public int userid { get; set; }
        public string name { get; set; }
        public Nullable<int> age { get; set; }
        public string picture { get; set; }
        public string cover { get; set; }
        public int positionid { get; set; }
        public string bio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<coach_associations> coach_associations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<coach_associations_request> coach_associations_request { get; set; }
        public virtual user user { get; set; }
        public virtual games_positions games_positions { get; set; }
    }
}
