//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsZone
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback
    {
        public int id { get; set; }
        public int C_to { get; set; }
        public int C_from { get; set; }
        public int rating { get; set; }
        public string msg { get; set; }
        public System.DateTime C_date { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
